#!/bin/sh

export PATH="./node_modules/.bin:$PATH"

git stash -ku

trap "git stash pop" EXIT

staged=$(git --no-pager diff --staged --name-only | grep -E '\.(js|ts)$')

if [ -n "$staged" ]
	then make verify
fi
