name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  npm-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Install Node.js
        run: volta install node

      - name: Install pnpm
        run: volta install pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run test
        run: npm t
